# Generated by Django 5.2.15 on 2026-07-17 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('credit', 'Credit')], default='cash', max_length=10),
        ),
        migrations.CreateModel(
            name='CustomerCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('amount', models.FloatField(help_text='Positive = credit added, negative = credit consumed.')),
                ('payment_date', models.DateField()),
                ('source', models.CharField(choices=[('overpayment', 'Overpayment'), ('prepayment', 'Prepayment'), ('applied', 'Applied to debt')], max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa')], help_text='How the underlying cash was received — only set for Overpayment/Prepayment entries.', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('related_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_entries', to='sales.sale')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
    ]
