# Generated by Django 5.2.15 on 2026-10-07 21:56

import compliance.storage
import compliance.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0006_employee_is_food_handler_alter_rolepermission_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True, help_text='Untick once the instrument is retired.')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'equipment',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. SOP-001', max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('recall', 'Product recall'), ('complaint', 'Customer complaint handling'), ('pest_control', 'Pest control'), ('waste', 'Waste management'), ('hygiene', 'Cleaning, sanitation & hygiene schedule'), ('personal_hygiene', 'Personal hygiene & protective clothing'), ('quality_control', 'Quality control'), ('calibration', 'Equipment calibration'), ('supervision', 'Scheme of supervision and control'), ('other', 'Other')], default='other', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=10)),
                ('content', models.TextField()),
                ('owner', models.CharField(blank=True, help_text='Person responsible for this procedure.', max_length=150)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=150)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('public_health', 'Public Health Licence (manufacturing premises)'), ('business_permit', 'Single Business Permit'), ('kebs_permit', 'KEBS certification / permit'), ('scheme', 'Signed Scheme of Supervision and Control'), ('std_eas_38', 'KS EAS 38:2014 — Labelling of Pre-Packaged Foods (copy)'), ('std_eas_153', 'KS EAS 153:2018 — Packaged Drinking Water (copy)'), ('std_eas_459', 'KS EAS 459 — Code of Hygiene (copy)'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('issuing_authority', models.CharField(blank=True, max_length=150)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Leave blank if it does not expire.', null=True)),
                ('file', models.FileField(blank=True, help_text='PDF, image or Word document, up to 10 MB.', storage=compliance.storage.get_compliance_storage, upload_to='documents/%Y/', validators=[compliance.validators.validate_upload])),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', '-expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_date', models.DateField()),
                ('next_due_date', models.DateField()),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('calibrated_by', models.CharField(blank=True, help_text='Calibration laboratory or body.', max_length=150)),
                ('file', models.FileField(blank=True, help_text='PDF, image or Word document, up to 10 MB.', storage=compliance.storage.get_compliance_storage, upload_to='calibrations/%Y/', validators=[compliance.validators.validate_upload])),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='compliance.equipment')),
            ],
            options={
                'ordering': ['-calibration_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('issued_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('issuing_facility', models.CharField(blank=True, max_length=150)),
                ('file', models.FileField(blank=True, help_text='PDF, image or Word document, up to 10 MB.', storage=compliance.storage.get_compliance_storage, upload_to='medical/%Y/', validators=[compliance.validators.validate_upload])),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_certificates', to='employees.employee')),
            ],
            options={
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='PersonnelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('qualification', 'Qualification / certificate'), ('employment', 'Evidence of employment'), ('other', 'Other')], default='qualification', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('institution', models.CharField(blank=True, help_text='Awarding institution or employer.', max_length=150)),
                ('date_obtained', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, help_text='PDF, image or Word document, up to 10 MB.', storage=compliance.storage.get_compliance_storage, upload_to='personnel/%Y/', validators=[compliance.validators.validate_upload])),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_documents', to='employees.employee')),
            ],
            options={
                'ordering': ['employee__first_name', 'doc_type', '-date_obtained'],
            },
        ),
        migrations.CreateModel(
            name='PremisesRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_met', models.BooleanField(default=False)),
                ('confirmed_on', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='compliance.procedure')),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
