# Generated by Django 5.2.15 on 2026-07-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('sales', 'Sales'), ('contacts', 'Customer Contacts'), ('maintenance', 'Pricing'), ('reports', 'Reports'), ('expenses', 'Expenses'), ('debts', 'Debts Management'), ('mpesa', 'M-Pesa'), ('water_test', 'Lab Test'), ('inventory', 'Inventory Management'), ('employees', 'Employee Management'), ('crm', 'Customer Relationship Management'), ('system_info', 'Settings')], max_length=30),
        ),
    ]
