# Generated by Django 5.2.15 on 2026-07-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_rolepermission_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='commission_earned',
            field=models.FloatField(default=0, help_text="Auto-computed total of the employee's earned commission within this period."),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('sales', 'Sales'), ('contacts', 'Customer Contacts'), ('maintenance', 'Pricing'), ('reports', 'Reports'), ('expenses', 'Expenses'), ('debts', 'Debts Management'), ('mpesa', 'M-Pesa'), ('water_test', 'Lab Test'), ('inventory', 'Inventory Management'), ('employees', 'Employee Management'), ('crm', 'Customer Relationship Management'), ('finance', 'Finance'), ('purchasing', 'Purchasing'), ('commissions', 'Commissions'), ('system_info', 'Settings')], max_length=30),
        ),
    ]
