# Generated by Django 5.2.15 on 2026-10-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_payroll_commission_earned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_food_handler',
            field=models.BooleanField(default=True, help_text='Handles product or works in the production area — needs a valid medical certificate (see Compliance).'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('sales', 'Sales'), ('contacts', 'Customer Contacts'), ('maintenance', 'Pricing'), ('reports', 'Reports'), ('expenses', 'Expenses'), ('debts', 'Debts Management'), ('mpesa', 'M-Pesa'), ('water_test', 'Lab Test'), ('inventory', 'Inventory Management'), ('employees', 'Employee Management'), ('crm', 'Customer Relationship Management'), ('finance', 'Finance'), ('purchasing', 'Purchasing'), ('commissions', 'Commissions'), ('daily_reconciliation', 'Daily Reconciliation'), ('ml_integration', 'Data Analytics'), ('system_info', 'Settings'), ('compliance', 'Compliance (KEBS)')], max_length=30),
        ),
    ]
