# Generated by Django 5.2.15 on 2026-09-29 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Failed login'), ('action', 'Action')], default='action', max_length=15)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('module', models.CharField(blank=True, max_length=50)),
                ('view_name', models.CharField(blank=True, max_length=150)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['-date_created'], name='core_activi_date_cr_25cbc9_idx'), models.Index(fields=['module'], name='core_activi_module_0a33cd_idx'), models.Index(fields=['event_type'], name='core_activi_event_t_12f68f_idx')],
            },
        ),
    ]
