# Generated by Django 5.2.15 on 2026-07-08 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='related_purchase_order',
            field=models.ForeignKey(blank=True, help_text='Optional — link this bill to a Purchasing-module purchase order (the Invoice step).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='purchasing.purchaseorder'),
        ),
    ]
