# Generated by Django 5.2.15 on 2026-07-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_bill_related_purchase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategoryaccountmapping',
            name='category',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pettycashvoucher',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
