# Generated by Django 5.2.15 on 2026-09-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_field', models.TextField()),
                ('meta_value', models.TextField()),
            ],
            options={
                'db_table': 'system_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduledTaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='backup', max_length=50)),
                ('source', models.CharField(choices=[('cron', 'Cron'), ('manual', 'Manual')], default='cron', max_length=10)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('failed', 'Failed')], max_length=10)),
                ('output', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
