# Generated by Django 5.2.15 on 2026-07-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Lunch', 'Lunch'), ('Token', 'Token'), ('Rent', 'Rent'), ('Water Bill', 'Water Bill'), ('Bottles', 'Bottles'), ('Non-Spills', 'Non-Spills'), ('Bike Repairs', 'Bike Repairs'), ('Salaries', 'Salaries'), ('Licenses', 'Licenses'), ('Service Charge', 'Service Charge'), ('Other', 'Other')], max_length=255)),
                ('amount', models.FloatField()),
                ('date_created', models.DateTimeField()),
                ('status', models.SmallIntegerField(choices=[(0, 'Unpaid'), (1, 'Paid (Cash)'), (2, 'Paid (M-Pesa)')], default=0)),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-date_created'],
                'managed': False,
            },
        ),
    ]
