# Generated by Django 5.2.15 on 2026-07-08 21:08

import django.db.models.deletion
import mpesa.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionType', models.CharField(blank=True, max_length=255, null=True)),
                ('TransID', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('TransTime', models.CharField(blank=True, max_length=255, null=True)),
                ('TransAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('BusinessShortCode', models.CharField(blank=True, max_length=255, null=True)),
                ('BillRefNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('InvoiceNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('OrgAccountBalance', models.CharField(blank=True, max_length=255, null=True)),
                ('ThirdPartyTransID', models.CharField(blank=True, max_length=255, null=True)),
                ('MSISDN', models.CharField(blank=True, max_length=255, null=True)),
                ('FirstName', models.CharField(blank=True, max_length=255, null=True)),
                ('MiddleName', models.CharField(blank=True, max_length=255, null=True)),
                ('LastName', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'mpesa_transactions',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, help_text='Prefills the STK Push field. Also required for Direct Payment to auto-reconcile.', max_length=20)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=mpesa.models._default_expiry)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_via', models.CharField(blank=True, choices=[('stk', 'STK Push'), ('direct', 'Direct Payment'), ('manual', 'Manual (staff)')], max_length=10)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sales', models.ManyToManyField(related_name='payment_links', to='sales.sale')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='MpesaC2BTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(max_length=100, unique=True)),
                ('trans_time', models.CharField(blank=True, max_length=20)),
                ('trans_amount', models.FloatField()),
                ('business_short_code', models.CharField(blank=True, max_length=20)),
                ('bill_ref_number', models.CharField(blank=True, max_length=100)),
                ('msisdn', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('raw_payload', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('duplicate', 'Duplicate (already paid via another channel)'), ('ignored', 'Ignored')], default='unmatched', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('matched_payment_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c2b_transactions', to='mpesa.paymentlink')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='STKPushAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('merchant_request_id', models.CharField(blank=True, max_length=100)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout')], default='requested', max_length=10)),
                ('result_code', models.CharField(blank=True, max_length=10)),
                ('result_desc', models.CharField(blank=True, max_length=255)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('payment_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stk_attempts', to='mpesa.paymentlink')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
