# Generated by Django 5.2.15 on 2026-09-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0002_legacytransactionallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(choices=[('stk_callback', 'STK Callback'), ('c2b_confirmation', 'C2B Confirmation')], max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
