# Generated by Django 5.2.15 on 2026-07-07 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Membranes', 'Membranes'), ('Ozone', 'Ozone'), ('UV Lamps', 'UV Lamps'), ('Chemicals', 'Chemicals'), ('Bottle Caps', 'Bottle Caps'), ('Labels', 'Labels'), ('Bottles', 'Bottles'), ('Jars', 'Jars'), ('Shrink Wrap', 'Shrink Wrap'), ('Other', 'Other')], max_length=50)),
                ('unit', models.CharField(choices=[('pieces', 'pieces'), ('liters', 'liters'), ('kg', 'kg'), ('rolls', 'rolls'), ('meters', 'meters'), ('other', 'other')], default='pieces', max_length=20)),
                ('current_stock', models.FloatField(default=0)),
                ('reorder_level', models.FloatField(default=0)),
                ('unit_cost', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('wastage', 'Wastage / Expired')], max_length=20)),
                ('quantity', models.FloatField(help_text='Positive = stock in, negative = stock out')),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.rawmaterial')),
            ],
            options={
                'ordering': ['-date_created', '-id'],
            },
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='default_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='inventory.supplier'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit_cost', models.FloatField(default=0)),
                ('purchase_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='inventory.rawmaterial')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier')),
            ],
            options={
                'ordering': ['-purchase_date', '-id'],
            },
        ),
    ]
