# Generated by Django 5.2.15 on 2026-08-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_reconciliation', '0002_cashdepositallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdepositallocation',
            name='depositor_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
