# Generated by Django 5.2.15 on 2026-08-02 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_reconciliation', '0003_cashdepositallocation_depositor_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashdepositallocation',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterField(
            model_name='cashdepositallocation',
            name='reconciliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='daily_reconciliation.dailyreconciliation'),
        ),
    ]
