# Generated by Django 5.2.15 on 2026-08-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_reconciliation', '0004_alter_cashdepositallocation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdepositallocation',
            name='trans_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
