# Generated by Django 5.2.15 on 2026-07-07 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JarType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('pricing', models.FloatField()),
                ('has_stock', models.CharField(blank=True, max_length=10, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('volume_value', models.FloatField(blank=True, null=True)),
                ('volume_unit', models.CharField(choices=[('ml', 'ml'), ('L', 'L')], default='L', max_length=2)),
            ],
            options={
                'db_table': 'jar_types',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JarTypeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_sale', models.FloatField(default=1, help_text='Units of this material consumed per 1 unit of the product sold.')),
                ('jar_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_usages', to='maintenance.jartype')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jar_type_usages', to='inventory.rawmaterial')),
            ],
            options={
                'ordering': ['material__category', 'material__name'],
                'constraints': [models.UniqueConstraint(fields=('jar_type', 'material'), name='unique_jar_type_material')],
            },
        ),
    ]
