# Generated by Django 5.2.15 on 2026-07-12 00:27

import commissions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('employees', '0005_payroll_commission_earned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.FloatField(default=0.15, help_text='Enter as a fraction — e.g. 0.15 for 15%.')),
                ('onboarding_date', models.DateField(default=commissions.models._today, help_text="Commission accrues on this customer's paid sales for 3 months from this date.")),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('account_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_accounts', to='employees.employee')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_accounts', to='contacts.contact')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
