# Generated by Django 5.2.15 on 2026-07-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.TextField()),
                ('type', models.SmallIntegerField(choices=[(1, 'Walk-In'), (2, 'For Delivery')], default=1)),
                ('delivery_address', models.TextField(blank=True)),
                ('amount', models.FloatField(default=0)),
                ('status', models.SmallIntegerField(choices=[(0, 'Unpaid'), (1, 'Paid (Cash)'), (2, 'Paid (M-Pesa)'), (3, 'Unresolved')], default=0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'sales',
                'ordering': ['-date_created'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('total_amount', models.FloatField()),
            ],
            options={
                'db_table': 'sales_items',
                'managed': False,
            },
        ),
    ]
